### ISSUE TITLE
Using Webpack to build with npm modules, but require() not found

### ISSUE THREAD

**Issue by lasergoat** [dollarshaveclub/cloudworker#95] opened 2019-06-17 20:37 UTC
I am running my cloudflare worker scripts in 3 ways:

1. in cloudflare itself
2. locally with this repo and npm test
3. locally with this repo in the cli: `cloudworker --port 3100 --debug --watch script-1.js`

----

**For item 1**, When I work on a script, I build with webpack, and deploy to cloudflare. So, if the script uses require('lodash') it runs fine because webpack puts lodash into the script and cloudflare runs it fine.

**For item 2**, it also works fine because before each test when I make an instance of the worker I pass in a reference to `require`. eg.

```
  this.beforeEach(() => {
    // clear out the spy
    fetchSpy.resetHistory();

    Object.assign(
      global,
      new (require("@dollarshaveclub/cloudworker"))(
        require("fs").readFileSync("script1.js", "utf8"),
        {
          bindings: {
            fetch: fetchSpy,
            addEventListener: addEventListenerSpy,
            require // <---------- passing in REQUIRE
          }
        }
      ).context
    );
  });
```

However, for **item number 3** when I run locally in the cli I have this:

```
// package.json
// ...
"start": "cloudworker --port 3100 --debug --watch script1.js",
```

How do I pass in a binding to require for running locally in the cli? Without a fix, when dollarshaveclub/cloudworker repo runs my code it throws an error because `require()` doesn't exist, and my script is trying to require lodash.

So far, I have got it working by adjusting the code in `bin/cloudworker.js` like:

```
  const opts = {
    debug: program.debug,
    enableCache: program.enableCache,
    bindings: { ...bindings, require } // always add require..
  };
```

obviously this isn't ideal, but I couldn't figure out how else to do it through the cli options.

**Comment by hankjacobs** [comment] 2019-06-18 00:45
You shouldn’t need to. Cloudworker was designed around the idea that one would pass in the same script that gets uploaded to Cloudflare (already webpack’ed).

**Comment by hankjacobs** [comment] 2019-06-18 00:53
Closing for now. If webpacking your script prior to running with cloudworker doesn’t work, feel free to reopen. Thanks!

**Closed by hankjacobs** 2019-06-18 00:53 UTC

**Comment by lasergoat** [comment] 2019-06-19 15:24
@hankjacobs sorry, i don't understand your response...

> You shouldn’t need to.

I shouldn't need to what? Are you saying that locally I need to have the cli run my webpacked code instead?

like:

```cloudworker --port 3100 --debug --watch dist/script.js```

**Comment by hankjacobs** [comment] 2019-06-19 15:35
Exactly. You shouldn’t need to bind `require` since the webpacked code shouldn’t have any require statements.

**Comment by lasergoat** [comment] 2019-06-20 16:50
@hankjacobs ok awesome, I'm with you now. The goal is to have Webpack generate a string or a file and feed that into the cloud worker. 

I'm not a Webpack pro so I used two separate commands like:

```npm start
# and in another tab...
npm run start:worker

# "start": "webpack --watch",
# "start:worker": "cloudworker --port 3100 --debug --watch dist/output.bundle.js",
```

Is there a cleaner way to do it with webpack? I'm no Webpack pro, but I'm searching their docs and thought I'd just ask also.

**Comment by lasergoat** [comment] 2019-06-20 21:04
Here's my npm-run-all solution:

```
// package.json...
// run-p == npm-run-all --parallel

  "scripts": {
    "start": "NODE_ENV=development run-p build:watch cfworker:pm",
    "start:redirects": "NODE_ENV=development run-p build:watch cfworker:redirects",
    "build": "webpack",
    "build:watch": "webpack --watch",
    "cfworker:pm": "cloudworker --port 3100 --debug --watch dist/scriptPaymentMethods.bundle.js",
    "cfworker:redirects": "cloudworker --port 3100 --debug --watch dist/scriptRedirects.bundle.js",
    "deploy:local": "source .env && npm run build && sh deploy.sh",
    "test": "mocha",
    "test:watch": "mocha -w"
  },
```

it's not the most scalable solution since anytime I add a script I'd need to make a new command, BUT it does work for now.

But I wanted to see if someone had a cleaner solution that npm-run-all for feeding Webpack builds into cloud worker with a watch.
